# Generated by Django 5.2.6 on 2025-10-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('biografia', models.TextField()),
            ],
        ),
    ]
