# Generated by Django 5.2.6 on 2025-10-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_biblioteca', '0002_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liv_Aut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_biblioteca.autor')),
            ],
        ),
    ]
