# Generated by Django 5.2.6 on 2025-10-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_biblioteca', '0004_categoria_liv_categ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Associacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('num_identificacao', models.IntegerField()),
                ('email', models.CharField()),
                ('data_cadastro', models.DateField()),
                ('id_associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_biblioteca.nivel_associacao')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('data_devolucao_limite', models.DateField()),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_biblioteca.livro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_biblioteca.usuario')),
            ],
        ),
    ]
