# Generated by Django 5.2.6 on 2025-10-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_biblioteca', '0005_nivel_associacao_usuario_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome',
        ),
    ]
