# Generated by Django 5.2.8 on 2025-11-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_personagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personagem_habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_personagens.habilidade')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_personagens.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacionamento', models.CharField(choices=[('RF', 'RELACIONAMENTO FAMILIAR'), ('RA', 'RELACIONAMENTO AMOROSO'), ('RAZ', 'RELACIONAMENTO DE AMIZADE'), ('RP', 'RELACIONAMENTO PROFISSIONAL')], max_length=3)),
                ('personagem1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagem1', to='api_personagens.personagem')),
                ('personagem2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagem2', to='api_personagens.personagem')),
            ],
        ),
    ]
