# Generated by Django 5.2.8 on 2025-11-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_personagens', '0002_habilidade_personagem_habilidades_relacionamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personagem_habilidades',
            new_name='PersonagemHabilidades',
        ),
    ]
